changelog:
  exclude:
    labels:
      - documentation
      - ci-cd
  categories:
    - title: DirkBuildTool
      labels:
        - build-tool
    - title: Features
      labels:
        - enhancement
    - title: Bugs and Optimizations
      labels:
        - bug
    - title: Other
      labels:
        - "*"
