changelog:
  exclude:
    labels:
      - documentation
  categories:
    - title: Build Tool
      labels:
        - build-tool
    - title: Rendering
      labels:
        - renderer
    - title: Platform
      labels:
        - platform
    - title: Other Features
      labels:
        - enhancement
    - title: Bugs and Optimizations
      labels:
        - bug
    - title: Other
      labels:
        - "*"
